from django.urls import path

from .views import (
    analysis_summary,
    delete_user,
    login_user,
    menu_tree,
    register_user,
    update_password,
    update_user,
    upload_avatar,
    user_page,
    actionlog_statistics,
    actionlog_page_ranking,
    actionlog_weekly_data,
    actionlog_monthly_day_data,
    analysis_province_sales,
    analysis_shop_sales,
    analysis_style_price,
    analysis_pattern_price,
    analysis_fabric_price,
    analysis_fit_price,
)

urlpatterns = [
    path("summary/", analysis_summary),
    path("user/login", login_user),
    path("user/add", register_user),
    path("user/page", user_page),
    path("user/<int:user_id>", update_user),
    path("user/password/<int:user_id>", update_password),
    path("user/avatar/<int:user_id>", upload_avatar),
    path("user/delete/<int:user_id>", delete_user),
    path("menu/getMenuTree/<int:user_id>", menu_tree),
    path("actionLog/statistics", actionlog_statistics),
    path("actionLog/pageRanking", actionlog_page_ranking),
    path("actionLog/weeklyData", actionlog_weekly_data),
    path("actionLog/monthlyDayData", actionlog_monthly_day_data),
    path("analysis/province-Sales", analysis_province_sales),
    path("analysis/shop-sales", analysis_shop_sales),
    path("analysis/shop-sales", analysis_shop_sales),
    path("analysis/style-price", analysis_style_price),
    path("analysis/pattern-price", analysis_pattern_price),
    path("analysis/fabric-price", analysis_fabric_price),
    path("analysis/fit-price", analysis_fit_price),
]
